---
version: '3'

services:
  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    ports:
      - 8888:8888  # access the app at localhost:8888
      - 5555:5555  # access webpack bundle analyzer at localhost:5555
    links:
      - backend
    environment:
      - NODE_ENV=production
      - API_HOST=backend
      - API_PORT=5000
    entrypoint:
      - /frontend-entrypoint.sh
    volumes:
      - ./frontend:/src

  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    environment:
      - FLASK_APP=app
      - FLASK_ENV=production
    entrypoint:
      - /flask-entrypoint.sh
    ports:
      - 5000:5000
    volumes:
      - ./backend:/app
